[HOPSWORKS-CLOUD-1656] Missing tour files after upgrade
logicalclocks/tensorflow-chef pull request #147
Opened 2021-03-05 09:18 UTC by maismail

2021-03-05 11:04 UTC, kouzant requested changes

2021-03-05 11:04 UTC, kouzant commented on recipes/default.rb
> +is_head_node = exists_local("hopsworks", "default") && !node['install']['cloud'].empty?
Attribute `install/cloud` is also set when we install Hopsworks on the cloud but not the managed version in hopsworks.ai You should check if if the `cloud` cookbook is present like https://github.com/logicalclocks/hopsworks-chef/blob/master/recipes/default.rb#L848

2021-03-05 11:18 UTC, maismail commented on recipes/default.rb
> +is_head_node = exists_local("hopsworks", "default") && !node['install']['cloud'].empty?
@kouzant Fixed in the last commit. If this ok, i'll cherry-pick to other PRs

2021-03-05 12:55 UTC, kouzant approved these changes

2021-03-08 09:18 UTC, kouzant approved these changes

2021-03-08 12:58 UTC, merged